# Generated by Django 6.1.1 on 2026-10-05 14:11

import django.db.models.deletion
import django.utils.timezone
import proctoring.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_resume_intelligence_remove_cheatingevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "api_key_prefix",
                    models.CharField(editable=False, max_length=16, unique=True),
                ),
                ("api_key_hash", models.CharField(editable=False, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("default_policy", models.CharField(default="standard", max_length=20)),
                ("webhook_url", models.URLField(blank=True)),
                (
                    "webhook_secret",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "evidence_retention_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProctorSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "external_ref",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("policy_name", models.CharField(default="standard", max_length=20)),
                ("policy_overrides", models.JSONField(blank=True, default=dict)),
                ("policy_fingerprint", models.CharField(blank=True, max_length=32)),
                ("policy_version", models.CharField(blank=True, max_length=20)),
                ("accommodations", models.JSONField(blank=True, default=list)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("preflight", "Pre-flight checks"),
                            ("active", "Active"),
                            ("paused", "Paused (disconnected)"),
                            ("completed", "Completed"),
                            ("terminated", "Terminated by policy"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=12,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("clear", "Clear"),
                            ("review", "Needs human review"),
                            ("fail", "Failed (terminated)"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("risk_score", models.FloatField(default=0.0)),
                ("cumulative_score", models.FloatField(default=0.0)),
                ("strikes", models.PositiveSmallIntegerField(default=0)),
                ("max_action", models.PositiveSmallIntegerField(default=0)),
                ("termination_reason", models.CharField(blank=True, max_length=255)),
                ("consent_at", models.DateTimeField(blank=True, null=True)),
                ("consent_version", models.CharField(blank=True, max_length=20)),
                ("consent_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("baseline", models.JSONField(blank=True, default=dict)),
                ("detector_state", models.JSONField(blank=True, default=dict)),
                ("reference_embedding", models.JSONField(blank=True, null=True)),
                ("first_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("ua_hash", models.CharField(blank=True, max_length=64)),
                (
                    "last_heartbeat",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("disconnected_at", models.DateTimeField(blank=True, null=True)),
                ("reconnect_count", models.PositiveSmallIntegerField(default=0)),
                ("telemetry_seq", models.BigIntegerField(default=-1)),
                ("frames_analyzed", models.PositiveIntegerField(default=0)),
                ("frames_dropped", models.PositiveIntegerField(default=0)),
                ("event_seq", models.PositiveIntegerField(default=0)),
                (
                    "chain_head",
                    models.CharField(
                        default="0000000000000000000000000000000000000000000000000000000000000000",
                        max_length=64,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "retention_until",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("erased_at", models.DateTimeField(blank=True, null=True)),
                (
                    "interview",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proctor_session",
                        to="core.interview",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="proctoring.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProctorEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("seq", models.PositiveIntegerField()),
                ("ts", models.FloatField()),
                ("source", models.CharField(max_length=12)),
                ("kind", models.CharField(db_index=True, max_length=40)),
                ("category", models.CharField(blank=True, max_length=16)),
                ("severity", models.PositiveSmallIntegerField(default=0)),
                ("confidence", models.FloatField(default=0.0)),
                ("points", models.FloatField(default=0.0)),
                ("strike", models.BooleanField(default=False)),
                ("counted", models.BooleanField(default=False)),
                ("action", models.PositiveSmallIntegerField(default=0)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("evidence_sha256", models.CharField(blank=True, max_length=64)),
                ("prev_hash", models.CharField(max_length=64)),
                ("hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="proctoring.proctorsession",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "seq"],
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to=proctoring.models.evidence_path)),
                ("sha256", models.CharField(max_length=64)),
                ("size", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidence_items",
                        to="proctoring.proctorevent",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="proctoring.proctorsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=40)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed (gave up)"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("last_error", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="proctoring.proctorsession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="proctoring.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="proctorevent",
            index=models.Index(
                fields=["session", "counted", "ts"], name="proctor_event_counted_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="proctorevent",
            constraint=models.UniqueConstraint(
                fields=("session", "seq"), name="proctor_event_seq_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="proctorsession",
            index=models.Index(
                fields=["state", "last_heartbeat"], name="proctor_state_hb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proctorsession",
            index=models.Index(
                fields=["tenant", "-created_at"], name="proctor_tenant_idx"
            ),
        ),
    ]
