# Generated by Django 6.1.1 on 2026-10-05 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_evaluation_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cheatingevent",
            name="cheating_interview_idx",
        ),
        migrations.AddField(
            model_name="resume",
            name="content_sha256",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="resume",
            name="integrity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="resume",
            name="owner_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="parse_confidence",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="resume",
            name="parse_schema_version",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="resume",
            name="probe_plan",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="resume",
            name="simhash",
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="interview",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="interview",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("terminated", "Terminated (Cheating)"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="strikes",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="skill_tag",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="resume",
            name="candidate_name",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="resume",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="experience_years",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="file",
            field=models.FileField(
                upload_to="resumes/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "docx", "txt"]
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["interview", "created_at"], name="question_interview_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resume",
            index=models.Index(fields=["candidate_name"], name="resume_name_idx"),
        ),
        migrations.DeleteModel(
            name="CheatingEvent",
        ),
    ]
